### ISSUE TITLE
Command failed: code -r H:\vscode-workspace\markList.code-workspace

### ISSUE THREAD

**Issue by QS20199** [sadesyllas/vscode-workspace-switcher#1]
Hello, I find your extension and it may be good use for me! That's great, but there is something wrong with it.

I set this config:

```
"vscodeWorkspaceSwitcher.paths": ["H:/vscode-workspace/"]
```

and workspace files are the following: 

![image](https://user-images.githubusercontent.com/7935557/32818949-6be1eec8-ca01-11e7-9644-2ab4d996768c.png)

when I try to switch workspace, an error occurred:

![default](https://user-images.githubusercontent.com/7935557/32818917-3a75279c-ca01-11e7-9ab8-2cf4c02e88c2.JPG)

did I make something wrong? or any bug in your extension?

thanks!

**Comment by sadesyllas** [comment]
Hi @QS20199!

Could you please change from `H:/vscode-workspace/` to `H:\\vscode-workspace`?

I don't currently have a windows pc available but I will do so tomorrow.

Until then, please try the above.

**Comment by QS20199** [comment]
I tried, and it was the same.

I am sure that the 'node' is in my path, and if I execute 'code -r H:/vscode-workspace/markList.code-workspace', it can work.

**Comment by ericamigo** [comment]
having the same error. uninstalled the plugin temporarily :)

**Comment by sadesyllas** [comment]
@QS20199, @ericamigo, I work solely on VS Code Insiders so I do not have this issue.

I tested with VS Code and I had the same issue.

When the extension tries to run `code` it actually runs another program it seems (I don't know what goes wrong with the path in windows there). I can confirm the following:

1. When I manually run the required command from `cmd` it works
2. If I rename `C:\Program Files\Microsoft VS Code\bin\code.cmd` to `C:\Program Files\Microsoft VS Code\bin\codefoo.cmd` and change the extension code to try to run `codefoo` it also works.

So I don't know what goes wrong with the windows path at that point but `code-insiders`, not being simply `code` always runs the correct executable. I will try this in Linux as well to make sure it's a windows thing.

**Comment by kromakollision** [comment]
I have a similar issue (VS Code on Windows 7)
Settings file:
```
"vscodeWorkspaceSwitcher.paths": [
        "C:/projects/_vscode.projects"
    ]
```
output:
`Command failed: code -n C:\projects_vscode.projects\sample-project.code-workspace`
Notice the missing "\" between `C:\projects` and `_vscode.projects`

**Comment by ugurozturk** [comment]
I have smilar error.

**Comment by joonro** [comment]
I have a similar error as well, When I hover my cursor on the error message, it shows `bad option: -n`.

```
Command failed: code -n C:\Users\joon\Dropbox\Online\Online.code-workspace
```

**Comment by ugurozturk** [comment]
Installed Visual Studio Code Insiders and tried to run it. And it did work.

**Comment by ugurozturk** [comment]
@sadesyllas i have an idea. What about calling code.exe by also dynamic editable parameter ? in the settings let us to give the location of the code.exe so it will do like

`C:\\Program Files\\Microsoft VS Code Insiders\\code.exe -n location-of-codeworkspace`

**Comment by sadesyllas** [comment]
@ugurozturk thank you for your suggestion.
In the next couple of days I will try to find a way to get the absolute path of the executable automatically.
If I cannot do so in a generic way, I' ll implement your idea so as to render the extension usable with VS Code.

**Comment by sadesyllas** [comment]
Ok, I have implemented what @ugurozturk has proposed in v1.4.0:

By setting `vscodeWorkspaceSwitcher.codeExecutable` explicitly, e.g. to `C:\Program Files\Microsoft VS Code\bin\code.cmd`, you should be fine.

I could not make heads or tails as to why trying to find `code` in windows results in running another, arbitrary program, which I cannot even find in my system. I can run `code` from my command line just fine but through VS Code it seems that there is some confusion as to which executable is finally found in `PATH`.

**Comment by QS20199** [comment]
it works! thx~

**Comment by ugurozturk** [comment]
@sadesyllas yeah it is works now. Just in keeping here who still doesn't fix it.
"vscodeWorkspaceSwitcher.codeExecutable": "C:\\Program Files\\Microsoft VS Code\\bin\\code",
